<?php
/*
* Plugin Name: Cities Dropdown for WooCommerce Add New Order
* Plugin URI: https://github.com/mdfathi99
* Description: Adds a dropdown of cities to the WooCommerce admin "Add new order" page based on the selected country and state.
* Version: 1.0.2
* Author: Mohammad Fathi Rahman
* Author URI: https://github.com/mdfathi99
**/

// add_filter( 'woocommerce_admin_billing_fields', 'admin_billing_city_select_field' );
// function admin_billing_city_select_field( $fields ) {
//     global $pagenow, $places;

//     // Only for new order creation
//     if( $pagenow != 'post-new.php' ) return $fields;

//     $options = array('' => __( 'Select a city&hellip;', 'woocommerce' ));
//     if(isset($places['BD'])){
//         foreach($places['BD'] as $key => $value){
//             $options[$key] = $value[0];
//         }
//     }
//     $fields['city'] = array(
//         'label'   => __( 'City', 'woocommerce' ),
//         'show'    => false,
//         'class'   => 'js_field-city select short',
//         'type'    => 'select',
//         'options' => $options,
//     );

//     return $fields;
// }

global $places;

$places['BD'] = array(
    'dhaka' => array(
        __('12 Tala', 'woocommerce'),
        __('Aam Bagan', 'woocommerce'),
        __('Abdullah Bag', 'woocommerce'),
        __('Abujar Bafari Gali', 'woocommerce'),
        __('Abul Hotel', 'woocommerce'),
        __('Addin Hospital', 'woocommerce'),
        __('Adorsho Nagor', 'woocommerce'),
        __('Aftab Nagor Block A To G', 'woocommerce'),
        __('Agora', 'woocommerce'),
        __('Alen Bari', 'woocommerce'),
        __('Arambag', 'woocommerce'),
        __('Arjot Para', 'woocommerce'),
        __('Ashalota, Bonolota', 'woocommerce'),
        __('Aurongojeb Road', 'woocommerce'),
        __('Baf Shaheen College/Jahangir Gate', 'woocommerce'),
        __('Baganbari', 'woocommerce'),
        __('Banani ', 'woocommerce'),
        __('Banani 1', 'woocommerce'),
        __('Banani 11', 'woocommerce'),
        __('Banani 17', 'woocommerce'),
        __('Banani 2', 'woocommerce'),
        __('Banani 21', 'woocommerce'),
        __('Banani 23', 'woocommerce'),
        __('Banani 27', 'woocommerce'),
        __('Banani 8', 'woocommerce'),
        __('Banani Chairman Bari', 'woocommerce'),
        __('Banani Dohs', 'woocommerce'),
        __('Bangshal', 'woocommerce'),
        __('Bashtola', 'woocommerce'),
        __('Bashundhara Block  A To L', 'woocommerce'),
        __('Bata Gali', 'woocommerce'),
        __('Begun Bari ', 'woocommerce'),
        __('Bepari Gali', 'woocommerce'),
        __('Bg Press', 'woocommerce'),
        __('Bhauya Para', 'woocommerce'),
        __('Biam Auditorium', 'woocommerce'),
        __('Bibirbagicha', 'woocommerce'),
        __('Bongsal', 'woocommerce'),
        __('Dhoar', 'woocommerce'),
        __('Boro Moghbazar', 'woocommerce'),
        __('Center Point', 'woocommerce'),
        __('Chairman Gali', 'woocommerce'),
        __('Channel 24', 'woocommerce'),
        __('Christian Para', 'woocommerce'),
        __('Cid Office', 'woocommerce'),
        __('Comilla Para', 'woocommerce'),
        __('Dalibari Kachabazar', 'woocommerce'),
        __('Demra', 'woocommerce'),
        __('Dillu Road', 'woocommerce'),
        __('Diplomatic Zone', 'woocommerce'),
        __('Dit Project', 'woocommerce'),
        __('Dnc Staff Quarter', 'woocommerce'),
        __('Doctor Goli', 'woocommerce'),
        __('Dokkhin Para', 'woocommerce'),
        __('East Goran', 'woocommerce'),
        __('East Nakhal Para', 'woocommerce'),
        __('East Noyatola', 'woocommerce'),
        __('East Rumpura', 'woocommerce'),
        __('Eskaton', 'woocommerce'),
        __('Fasertake', 'woocommerce'),
        __('Gm Bari', 'woocommerce'),
        __('Goran', 'woocommerce'),
        __('Graveyard Road', 'woocommerce'),
        __('Green Way', 'woocommerce'),
        __('Gudara Ghat', 'woocommerce'),
        __('Old Dhaka', 'woocommerce'),
        __('Gulbag', 'woocommerce'),
        __('Gulshan', 'woocommerce'),
        __('Gulshan 1', 'woocommerce'),
        __('Gulshan 2', 'woocommerce'),
        __('Gulshan Arong', 'woocommerce'),
        __('Gulshan Avenue', 'woocommerce'),
        __('Gupi Para', 'woocommerce'),
        __('Hazari Bari', 'woocommerce'),
        __('Imam Bag', 'woocommerce'),
        __('Jagonnath Pur', 'woocommerce'),
        __('Jourshara And Lichu Bagan', 'woocommerce'),
        __('Jurain', 'woocommerce'),
        __('Kajla', 'woocommerce'),
        __('Kakoli', 'woocommerce'),
        __('Kalachad Pur And Norda', 'woocommerce'),
        __('Kazi Office R Gali', 'woocommerce'),
        __('Kemal Ataturk Avenue', 'woocommerce'),
        __('Khilbarir Take', 'woocommerce'),
        __('Khilgaon', 'woocommerce'),
        __('Khilgaon Block A', 'woocommerce'),
        __('Khilgaon Block B', 'woocommerce'),
        __('Khilgaon Block C', 'woocommerce'),
        __('Krishi Market', 'woocommerce'),
        __('Kuni Para', 'woocommerce'),
        __('Kunipara', 'woocommerce'),
        __('Kuril Bisso Road', 'woocommerce'),
        __('Kuril Chaurasta', 'woocommerce'),
        __('Kuril Ghatpar', 'woocommerce'),
        __('Lalbag', 'woocommerce'),
        __('Lalmatia', 'woocommerce'),
        __('Link Road', 'woocommerce'),
        __('Lukaser Mor', 'woocommerce'),
        __('Maasranga Television', 'woocommerce'),
        __('Mailbag 1st Line', 'woocommerce'),
        __('Malibag', 'woocommerce'),
        __('Malibag Chowdhuripara', 'woocommerce'),
        __('Malitola', 'woocommerce'),
        __('Marul Badda', 'woocommerce'),
        __('Mirbag', 'woocommerce'),
        __('Mogbazar', 'woocommerce'),
        __('Mohakhali Bus Terminal', 'woocommerce'),
        __('Mohammadia Housing Limited', 'woocommerce'),
        __('Mohammadia Housing Ltd', 'woocommerce'),
        __('Mohammadpur', 'woocommerce'),
        __('Mohanagor Project', 'woocommerce'),
        __('Moinar Bag', 'woocommerce'),
        __('Monipuripara', 'woocommerce'),
        __('Motijheel', 'woocommerce'),
        __('Mouchak', 'woocommerce'),
        __('Navy Headquarters', 'woocommerce'),
        __('Nazimuddir Road', 'woocommerce'),
        __('Newmarket', 'woocommerce'),
        __('Nijhum Officers Quarters', 'woocommerce'),
        __('Niketon', 'woocommerce'),
        __('Nobin Bag', 'woocommerce'),
        __('Nobodoy Housing Ltd', 'woocommerce'),
        __('North Goran', 'woocommerce'),
        __('Notun Bag', 'woocommerce'),
        __('Nurjahan Road', 'woocommerce'),
        __('Paglamajar Gali', 'woocommerce'),
        __('Pakistan Embassy', 'woocommerce'),
        __('Panthapath', 'woocommerce'),
        __('Pc Culture Housing', 'woocommerce'),
        __('Police Plaza', 'woocommerce'),
        __('Post Office Road', 'woocommerce'),
        __('Postogola', 'woocommerce'),
        __('Prime Minister Office', 'woocommerce'),
        __('Prodan Muntri Karjaloy', 'woocommerce'),
        __('Provati Bag', 'woocommerce'),
        __('Purba Anchol Road', 'woocommerce'),
        __('Qatwali', 'woocommerce'),
        __('Radisson Water Blu Hotel', 'woocommerce'),
        __('Rajabazar', 'woocommerce'),
        __('Rampura Banassre', 'woocommerce'),
        __('Rampura Bazar', 'woocommerce'),
        __('Rampura Hazipara', 'woocommerce'),
        __('Rangs Vaban', 'woocommerce'),
        __('Razia Sultana Road', 'woocommerce'),
        __('Riaz Bag', 'woocommerce'),
        __('Roma Century ', 'woocommerce'),
        __('Rosulbag', 'woocommerce'),
        __('Sadhinata Tower', 'woocommerce'),
        __('Santibag', 'woocommerce'),
        __('Satrasta', 'woocommerce'),
        __('Satta Gali', 'woocommerce'),
        __('Sayed Nagor', 'woocommerce'),
        __('Shadhinota Sharoni', 'woocommerce'),
        __('Shahbag', 'woocommerce'),
        __('Shahidbag', 'woocommerce'),
        __('Shankar', 'woocommerce'),
        __('Shanti Niketon', 'woocommerce'),
        __('Shatar Kul', 'woocommerce'),
        __('Shekerteak', 'woocommerce'),
        __('Sheron Bag', 'woocommerce'),
        __('Shersah Suri Road', 'woocommerce'),
        __('Shubastu Najor Velly', 'woocommerce'),
        __('Shyamoli', 'woocommerce'),
        __('Siddiq Master Dhal', 'woocommerce'),
        __('Sipahi Bag', 'woocommerce'),
        __('Sismohol', 'woocommerce'),
        __('Soilmaid', 'woocommerce'),
        __('Soinik Club', 'woocommerce'),
        __('South Badda', 'woocommerce'),
        __('South Banassre', 'woocommerce'),
        __('South Goran', 'woocommerce'),
        __('Sukrabad', 'woocommerce'),
        __('Sur Soyad Road', 'woocommerce'),
        __('T&T Colony', 'woocommerce'),
        __('T&T Gali', 'woocommerce'),
        __('Tajmahal Road', 'woocommerce'),
        __('Taltola', 'woocommerce'),
        __('Tejgaon Industrial Area', 'woocommerce'),
        __('Tejgaon Link Road', 'woocommerce'),
        __('Tejgaon Truck Stand', 'woocommerce'),
        __('Tibet', 'woocommerce'),
        __('Town Hall', 'woocommerce'),
        __('Truck Stand', 'woocommerce'),
        __('United Hospital ', 'woocommerce'),
        __('Uttorpara', 'woocommerce'),
        __('Vatara', 'woocommerce'),
        __('Vodro Gali', 'woocommerce'),
        __('Vootergoli', 'woocommerce'),
        __('West Mailbag', 'woocommerce'),
        __('West Nakhal Para', 'woocommerce'),
        __('West Panthapath', 'woocommerce'),
        __('West Rumpura', 'woocommerce'),
        __('Wreless Gate', 'woocommerce'),
        __('Zigatala', 'woocommerce'),
        __('Baridhara', 'woocommerce'),
        __('Rampura', 'woocommerce'),
        __('Banasree', 'woocommerce'),
        __('Bashabo', 'woocommerce'),
        __('Moghbazar', 'woocommerce'),
        __('Tejgaon', 'woocommerce'),
        __('Mohakhali', 'woocommerce'),
        __('Mohakhali Dohs', 'woocommerce'),
        __('Banani', 'woocommerce'),
        __('Bashundhara R/A', 'woocommerce'),
        __('Notun Bazar', 'woocommerce'),
        __('Shahjadpur', 'woocommerce'),
        __('Norda', 'woocommerce'),
        __('Nakhalpara', 'woocommerce'),
        __('Farmgate', 'woocommerce'),
        __('Azimpur', 'woocommerce'),
        __('Dhaka University', 'woocommerce'),
        __('Kalabagan', 'woocommerce'),
        __('Elephant Road', 'woocommerce'),
        __('Asad Gate', 'woocommerce'),
        __('Hazaribag', 'woocommerce'),
        __('Adabar', 'woocommerce'),
        __('Chankharpul', 'woocommerce'),
        __('Nazimuddin Road', 'woocommerce'),
        __('Kamrangirchor', 'woocommerce'),
        __('Jatrabari', 'woocommerce'),
        __('Shantinagar', 'woocommerce'),
        __('Mugdapara', 'woocommerce'),
        __('Chakbazar', 'woocommerce'),
        __('Maniknagar', 'woocommerce'),
        __('Kamalapur', 'woocommerce'),
        __('Golapbag', 'woocommerce'),
        __('Paltan', 'woocommerce'),
        __('Gopibag', 'woocommerce'),
        __('Kakrail', 'woocommerce'),
        __('Tikatuli', 'woocommerce'),
        __('Shonir Akhra', 'woocommerce'),
        __('Gendaria', 'woocommerce'),
        __('Mirpur', 'woocommerce'),
        __('Mirpur 1', 'woocommerce'),
        __('Mirpur 2', 'woocommerce'),
        __('Mirpur 6', 'woocommerce'),
        __('Mirpur 7', 'woocommerce'),
        __('Mirpur 11', 'woocommerce'),
        __('Mirpur 12', 'woocommerce'),
        __('Mirpur Dohs', 'woocommerce'),
        __('Mirpur 10', 'woocommerce'),
        __('Mirpur 13', 'woocommerce'),
        __('Mirpur 14', 'woocommerce'),
        __('Kalshi', 'woocommerce'),
        __('Agargaon', 'woocommerce'),
        __('Shewrapara', 'woocommerce'),
        __('Kazipara', 'woocommerce'),
        __('Mirpur Cantonment', 'woocommerce'),
        __('Kallaynnpur', 'woocommerce'),
        __('Darus Salam', 'woocommerce'),
        __('Azampur', 'woocommerce'),
        __('Nikunjo 1', 'woocommerce'),
        __('Khilkhet', 'woocommerce'),
        __('Uttar Khan/Dakkhin Khan', 'woocommerce'),
        __('Kafrul', 'woocommerce'),
        __('Baridhara', 'woocommerce'),
        __('Baridhara Dohs', 'woocommerce'),
        __('Baridhara Block-J', 'woocommerce'),
        __('Shajadpur East', 'woocommerce'),
        __('Kuril', 'woocommerce'),
        __('Shipahibag', 'woocommerce'),
        __('Meradia', 'woocommerce'),
        __('Dhanmondi', 'woocommerce'),
        __('Dhanmondi 9a', 'woocommerce'),
        __('Dhanmondi R/A', 'woocommerce'),
        __('Dhanmondi 9', 'woocommerce'),
        __('Dhanmondi 8a', 'woocommerce'),
        __('Dhanmondi 8', 'woocommerce'),
        __('Dhanmondi 1', 'woocommerce'),
        __('Dhanmondi 2', 'woocommerce'),
        __('Dhanmondi 11a', 'woocommerce'),
        __('Dhanmondi 12a', 'woocommerce'),
        __('Dhanmondi 10a', 'woocommerce'),
        __('Dhanmondi 1a', 'woocommerce'),
        __('Dhanmondi 2a', 'woocommerce'),
        __('Dhanmondi 3', 'woocommerce'),
        __('Dhanmondi 4', 'woocommerce'),
        __('Dhanmondi 3a', 'woocommerce'),
        __('Dhanmondi 4a', 'woocommerce'),
        __('Dhanmondi 5a', 'woocommerce'),
        __('Dhanmondi 5', 'woocommerce'),
        __('Dhanmondi 6', 'woocommerce'),
        __('Dhanmondi 6a', 'woocommerce'),
        __('Dhanmondi 7', 'woocommerce'),
        __('Dhanmondi 7a', 'woocommerce'),
        __('Dhanmondi 10', 'woocommerce'),
        __('Dhanmondi 11', 'woocommerce'),
        __('Dhanmondi 12', 'woocommerce'),
        __('Dhanmondi 13', 'woocommerce'),
        __('Dhanmondi 16', 'woocommerce'),
        __('Dhanmondi 13a', 'woocommerce'),
        __('Dhanmondi 14a', 'woocommerce'),
        __('Dahnmondi 15a', 'woocommerce'),
        __('Dhanmondi 14', 'woocommerce'),
        __('Dhanmondi 15', 'woocommerce'),
        __('Dhanmondi 27', 'woocommerce'),
        __('Dhanmondi 31', 'woocommerce'),
        __('Dhanmondi 30', 'woocommerce'),
        __('Dhanmondi 32', 'woocommerce'),
        __('Green Road', 'woocommerce'),
        __('Vasan Tek', 'woocommerce'),
        __('Jakir Hussain Road', 'woocommerce'),
        __('Senpara', 'woocommerce'),
        __('Bais Teki', 'woocommerce'),
        __('Kochukhet', 'woocommerce'),
        __('Ibrahimpur', 'woocommerce'),
        __('Balughat', 'woocommerce'),
        __('Matikata', 'woocommerce'),
        __('Janata Housing', 'woocommerce'),
        __('Eastern Housing', 'woocommerce'),
        __('Pallabi', 'woocommerce'),
        __('Rupnagor', 'woocommerce'),
        __('Ahamedbag', 'woocommerce'),
        __('Tolarbag', 'woocommerce'),
        __('Ansar Camp', 'woocommerce'),
        __('Golarteak', 'woocommerce'),
        __('Pirerbag', 'woocommerce'),
        __('Paikpara', 'woocommerce'),
        __('Mazar Road', 'woocommerce'),
        __('Uttara', 'woocommerce'),
        __('Uttara Sector 1', 'woocommerce'),
        __('Uttara Sector 3', 'woocommerce'),
        __('Uttara Sector 4', 'woocommerce'),
        __('Uttara Sector 5', 'woocommerce'),
        __('Uttara Sector 6', 'woocommerce'),
        __('Uttara Sector 8', 'woocommerce'),
        __('Uttara Sector 7', 'woocommerce'),
        __('Uttara Sector 9', 'woocommerce'),
        __('Uttara Sector 10', 'woocommerce'),
        __('Uttara Sector 11', 'woocommerce'),
        __('Uttara Sector 12', 'woocommerce'),
        __('Uttara Sector 13', 'woocommerce'),
        __('Uttara Sector 14', 'woocommerce'),
        __('Uttara Jasimuddin', 'woocommerce'),
        __('Lake City', 'woocommerce'),
        __('Ashkona', 'woocommerce'),
        __('Nondipara', 'woocommerce'),
        __('Wari', 'woocommerce'),
        __('Foridabad', 'woocommerce'),
        __('Sadarghat', 'woocommerce'),
        __('Gulistan', 'woocommerce'),
        __('Nawabpur', 'woocommerce'),
        __('Lakshmibazar', 'woocommerce'),
        __('Shajahanpur', 'woocommerce'),
        __('Shutrapur', 'woocommerce'),
        __('Fokirapool', 'woocommerce'),
        __('Hazipara', 'woocommerce'),
        __('Baily Road', 'woocommerce'),
        __('Shaheenbag', 'woocommerce'),
        __('Rajarbag', 'woocommerce'),
        __('Abdullahpur', 'woocommerce'),
        __('Mirpur', 'woocommerce'),
        __('Badda', 'woocommerce'),
        __('Middle Badda', 'woocommerce'),
        __('North Badda', 'woocommerce'),
        __('Bordhon Bari', 'woocommerce'),
        __('West Rampura', 'woocommerce'),
        __('Kalachandpur', 'woocommerce'),
        __('Nurerchala', 'woocommerce'),
        __('Gopipara', 'woocommerce'),
        __('Manda', 'woocommerce'),
        __('Bongshal', 'woocommerce'),
        __('Bashundhara 300ft', 'woocommerce'),
        __('Kaderabad Housing', 'woocommerce'),
        __('Chan Mia Housing', 'woocommerce'),
        __('Mohanogor Project', 'woocommerce'),
        __('Dhanmondi 28', 'woocommerce'),
        __('Dhaka Housing', 'woocommerce'),
        __('Iqbal Road', 'woocommerce'),
        __('Asad Avenue', 'woocommerce'),
        __('Aziz Mohollah', 'woocommerce'),
        __('Babar Road', 'woocommerce'),
        __('Old Airport Road', 'woocommerce'),
        __('Bfdc Mor', 'woocommerce'),
        __('Shahjanpur', 'woocommerce'),
        __('Shonargoan', 'woocommerce'),
        __('Tejturi Bazar', 'woocommerce'),
        __('Kawran Bazar', 'woocommerce'),
        __('Fdc', 'woocommerce'),
        __('Noyatola', 'woocommerce'),
        __('Peyarabag', 'woocommerce'),
        __('Pollima', 'woocommerce'),
        __('Ansar Camp(Moghbazar)', 'woocommerce'),
        __('Khilgaon Taltola', 'woocommerce'),
        __('Tilpa Para', 'woocommerce'),
        __('Modhubag', 'woocommerce'),
        __('Ulon', 'woocommerce'),
        __('Aftab Nagar', 'woocommerce'),
        __('Shatarkul', 'woocommerce'),
        __('Jamuna Future Park', 'woocommerce'),
        __('Aziz Sarani', 'woocommerce'),
        __('Coca-Cola', 'woocommerce'),
        __('Apollo Hospital', 'woocommerce'),
        __('Shoinik Club', 'woocommerce'),
        __('Bangladesh Betar', 'woocommerce'),
        __('Monipur', 'woocommerce'),
        __('Sony Cienema Hall', 'woocommerce'),
        __('South Bishil', 'woocommerce'),
        __('Bangla College', 'woocommerce'),
        __('Tolar Bag', 'woocommerce'),
        __('Technical', 'woocommerce'),
        __('Gabtoli', 'woocommerce'),
        __('Nikunjo 2', 'woocommerce'),
        __('Namapara', 'woocommerce'),
        __('Pink City', 'woocommerce'),
        __('Kawla', 'woocommerce'),
        __('Airport', 'woocommerce'),
        __('Haji Camp', 'woocommerce'),
        __('Koshai Bari', 'woocommerce'),
        __('Mollar Tek', 'woocommerce'),
        __('Prem Bagan', 'woocommerce'),
        __('Gawair', 'woocommerce'),
        __('Azampur Kacha Bazar', 'woocommerce'),
        __('Chalabon', 'woocommerce'),
        __('Rajlakhsmi', 'woocommerce'),
        __('House Building', 'woocommerce'),
        __('Diya Bari', 'woocommerce'),
        __('Uttara Residential Model Town', 'woocommerce'),
        __('Faydabad', 'woocommerce'),
        __('Kamarpara', 'woocommerce'),
        __('Baitul Aman Housing', 'woocommerce'),
        __('Bashbari', 'woocommerce'),
        __('Chand Uddan', 'woocommerce'),
        __('Geneva Camp', 'woocommerce'),
        __('Humayun Road', 'woocommerce'),
        __('Solimullah Road', 'woocommerce'),
        __('Sher Shah Suri Road', 'woocommerce'),
        __('Jafrabad', 'woocommerce'),
        __('Katasur', 'woocommerce'),
        __('Mohammadpur Thana (New)', 'woocommerce'),
        __('Rayer Bazar', 'woocommerce'),
        __('Modhu Bazar', 'woocommerce'),
        __('Khamar Bari', 'woocommerce'),
        __('Manik Mia Avenue', 'woocommerce'),
        __('Sobhanbag', 'woocommerce'),
        __('Tallabag', 'woocommerce'),
        __('West Razabazar', 'woocommerce'),
        __('Indira Road', 'woocommerce'),
        __('East Razabazar', 'woocommerce'),
        __('Kathalbagan', 'woocommerce'),
        __('Cresent Road', 'woocommerce'),
        __('North Road', 'woocommerce'),
        __('Central Road', 'woocommerce'),
        __('Hatirpool', 'woocommerce'),
        __('Paribag', 'woocommerce'),
        __('Science Lab', 'woocommerce'),
        __('Nilkhet', 'woocommerce'),
        __('Pilkhana', 'woocommerce'),
        __('Gonok Tuli', 'woocommerce'),
        __('Borhanpur', 'woocommerce'),
        __('Polashi', 'woocommerce'),
        __('Bakshi Bazar', 'woocommerce'),
        __('Baridhara Diplomatic', 'woocommerce'),
        __('Tb Gate', 'woocommerce'),
        __('Rasulbag', 'woocommerce'),
        __('Amtoli', 'woocommerce'),
        __('Korail Bosti', 'woocommerce'),
        __('Mohakhali Wireless', 'woocommerce'),
        __('Elenbari', 'woocommerce'),
        __('West Nakhalpara', 'woocommerce'),
        __('East Nakhalpara', 'woocommerce'),
        __('Nabisco', 'woocommerce'),
        __('Jahangir Gate', 'woocommerce'),
        __('Arjatpara', 'woocommerce'),
        __('Tejgaon Old Airport', 'woocommerce'),
        __('Joarsahara', 'woocommerce'),
        __('Banani (Chairman Bari)', 'woocommerce'),
        __('Mintu Road', 'woocommerce'),
        __('Shideshwari', 'woocommerce'),
        __('Shobujbag', 'woocommerce'),
        __('Basabo Patwary Goli', 'woocommerce'),
        __('Mather Tek', 'woocommerce'),
        __('Matuwail', 'woocommerce'),
        __('Dhonia', 'woocommerce'),
        __('Madinabag', 'woocommerce'),
        __('Rayerbag', 'woocommerce'),
        __('Islampur', 'woocommerce'),
        __('Patuatuli', 'woocommerce'),
        __('Shammibag', 'woocommerce'),
        __('Bonogram', 'woocommerce'),
        __('Tatibazar', 'woocommerce'),
        __('Kotowali', 'woocommerce'),
        __('Babubazar', 'woocommerce'),
        __('Mitford', 'woocommerce'),
        __('Nayabazar', 'woocommerce'),
        __('Chokbazar', 'woocommerce'),
        __('Siddiqbazar', 'woocommerce'),
        __('Saydabad', 'woocommerce'),
        __('Dilkusha', 'woocommerce'),
        __('Baytul Mokarrom', 'woocommerce'),
        __('Gpo', 'woocommerce'),
        __('Press Club', 'woocommerce'),
        __('Bijay Nagar', 'woocommerce'),
        __('Shegunbagicha', 'woocommerce'),
        __('Aga Sadiq Road', 'woocommerce'),
        __('Urdu Road', 'woocommerce'),
        __('Begumbazar', 'woocommerce'),
        __('Armanitola', 'woocommerce'),
        __('Nazirabazar', 'woocommerce'),
        __('Boro Shahebr Bazar', 'woocommerce'),
        __('Jagannath University', 'woocommerce'),
        __('Shakharibazar', 'woocommerce'),
        __('Narinda', 'woocommerce'),
        __('Chowdhury Para', 'woocommerce'),
        __('Kuratoli', 'woocommerce'),
        __('Bijoy Sharanani', 'woocommerce'),
        __('Demra', 'woocommerce'),
        __('Postogola', 'woocommerce'),
        __('Jurain', 'woocommerce'),
        __('Kajla', 'woocommerce'),
        __('Bibirbagicha', 'woocommerce'),
        __('Keraniganj Upazila Sadar', 'woocommerce'),
    ),
    'faridpur' => array(
        __('Alfadanga', 'woocommerce'),
        __('Bhanga', 'woocommerce'),
        __('Boalmari', 'woocommerce'),
        __('Char Bhadrasan', 'woocommerce'),
        __('Faridpur Sadar', 'woocommerce'),
        __('Madhukhali', 'woocommerce'),
        __('Nagarkanda', 'woocommerce'),
        __('Sadarpur', 'woocommerce'),
        __('Saltha', 'woocommerce'),
    ),
    'gazipur' => array(
        __('Gazipur Sadar', 'woocommerce'),
        __('Kaliakair', 'woocommerce'),
        __('Kaliganj', 'woocommerce'),
        __('Kapasia', 'woocommerce'),
        __('Sreepur', 'woocommerce'),
        __('Tongi', 'woocommerce'),
    ),
    'gopalganj' => array(
        __('Gopalganj Sadar', 'woocommerce'),
        __('Kashiani', 'woocommerce'),
        __('Kotalipara', 'woocommerce'),
        __('Muksudpur', 'woocommerce'),
        __('Tungipara', 'woocommerce'),
    ),
    'kishoreganj' => array(
        __('Austagram', 'woocommerce'),
        __('Bajitpur', 'woocommerce'),
        __('Bhairab', 'woocommerce'),
        __('Hossainpur', 'woocommerce'),
        __('Itna', 'woocommerce'),
        __('Karimganj', 'woocommerce'),
        __('Katiadi', 'woocommerce'),
        __('Kishoreganj Sadar', 'woocommerce'),
        __('Kuliar Char', 'woocommerce'),
        __('Mithamain', 'woocommerce'),
        __('Nikli', 'woocommerce'),
        __('Pakundia', 'woocommerce'),
        __('Tarail', 'woocommerce'),
    ),
    'madaripur' => array(
        __('Kalkini', 'woocommerce'),
        __('Madaripur Sadar', 'woocommerce'),
        __('Rajoir', 'woocommerce'),
        __('Shibchar', 'woocommerce'),
    ),
    'manikganj' => array(
        __('Daulatpur', 'woocommerce'),
        __('Ghior', 'woocommerce'),
        __('Harirampur', 'woocommerce'),
        __('Manikganj Sadar', 'woocommerce'),
        __('Saturia', 'woocommerce'),
        __('Shibalaya', 'woocommerce'),
        __('Singair', 'woocommerce'),
    ),
    'munshiganj' => array(
        __('Gazaria', 'woocommerce'),
        __('Lohajang', 'woocommerce'),
        __(' Munshiganj Sadar', 'woocommerce'),
        __('Serajdikhan', 'woocommerce'),
        __('Sreenagar', 'woocommerce'),
        __('Tongibari', 'woocommerce'),
    ),
    'narayanganj' => array(
        __('Araihazar', 'woocommerce'),
        __('Sonargaon', 'woocommerce'),
        __('Bandar', 'woocommerce'),
        __('Narayanganj Sadar', 'woocommerce'),
        __('Rupganj', 'woocommerce'),
    ),
    'narsingdi' => array(
        __('Belabo', 'woocommerce'),
        __('Manohardi', 'woocommerce'),
        __('Narsingdi Sadar', 'woocommerce'),
        __('Palash', 'woocommerce'),
        __('Roypura', 'woocommerce'),
        __('Shibpur', 'woocommerce'),
    ),
    'rajbari' => array(
        __('Baliakandi', 'woocommerce'),
        __('Goalanda', 'woocommerce'),
        __('Kalukhali', 'woocommerce'),
        __('Pangsha', 'woocommerce'),
        __('Rajbari Sadar', 'woocommerce'),
    ),
    'shariatpur' => array(
        __('Bhedarganj', 'woocommerce'),
        __('Damudya', 'woocommerce'),
        __('Gosairhat', 'woocommerce'),
        __('Naria', 'woocommerce'),
        __('Shariatpur Sadar', 'woocommerce'),
        __('Zanjira', 'woocommerce'),
    ),
    'tangail' => array(
        __('Basail', 'woocommerce'),
        __('Bhuapur', 'woocommerce'),
        __('Delduar', 'woocommerce'),
        __('Dhanbari', 'woocommerce'),
        __('Ghatail', 'woocommerce'),
        __('Gopalpur', 'woocommerce'),
        __('Kalihati', 'woocommerce'),
        __('Madhupur', 'woocommerce'),
        __('Mirzapur', 'woocommerce'),
        __('Nagarpur', 'woocommerce'),
        __('Sakhipur', 'woocommerce'),
        __('Tangail Sadar', 'woocommerce'),
    ),
    'barisal' => array(
        __('Agailjhara', 'woocommerce'),
        __('Babuganj', 'woocommerce'),
        __('Bakerganj', 'woocommerce'),
        __('Banari Para', 'woocommerce'),
        __('Gaurnadi', 'woocommerce'),
        __('Hizla', 'woocommerce'),
        __('Barisal Sadar (Kotwali)', 'woocommerce'),
        __('Mhendiganj', 'woocommerce'),
        __('Muladi', 'woocommerce'),
        __('Wazirpur', 'woocommerce'),
    ),
    'barguna' => array(
        __('Amtali', 'woocommerce'),
        __('Bamna', 'woocommerce'),
        __('Barguna Sadar', 'woocommerce'),
        __('Betagi', 'woocommerce'),
        __('Patharghata', 'woocommerce'),
        __('Taltali', 'woocommerce'),
    ),
    'bhola' => array(
        __(' Bhola Sadar', 'woocommerce'),
        __('Burhanuddin', 'woocommerce'),
        __('Char Fasson', 'woocommerce'),
        __('Daulat Khan', 'woocommerce'),
        __('Lalmohan', 'woocommerce'),
        __('Manpura', 'woocommerce'),
        __('Tazumuddin', 'woocommerce'),
    ),
    'jhalakati' => array(
        __('Jhalokati Sadar', 'woocommerce'),
        __('Kanthalia', 'woocommerce'),
        __('Nalchity', 'woocommerce'),
        __('Rajapur', 'woocommerce'),
    ),
    'patuakhali' => array(
        __('Bauphal', 'woocommerce'),
        __('Dashmina', 'woocommerce'),
        __('Dumki', 'woocommerce'),
        __('Galachipa', 'woocommerce'),
        __('Kalapara', 'woocommerce'),
        __('Mirzaganj', 'woocommerce'),
        __('Patuakhali Sadar', 'woocommerce'),
        __('Rangabali', 'woocommerce'),
    ),
    'pirojpur' => array(
        __('Bhandaria', 'woocommerce'),
        __('Kawkhali', 'woocommerce'),
        __('Mathbaria', 'woocommerce'),
        __('Nazirpur', 'woocommerce'),
        __('Pirojpur Sadar', 'woocommerce'),
        __('Nesarabad (Swarupkati)', 'woocommerce'),
        __('Zianagar', 'woocommerce'),
    ),
    'bandarban' => array(
        __('Alikadam', 'woocommerce'),
        __('Bandarban Sadar', 'woocommerce'),
        __('Lama', 'woocommerce'),
        __('Naikhongchhari', 'woocommerce'),
        __('Rowangchhari', 'woocommerce'),
        __('Ruma', 'woocommerce'),
        __('Thanchi', 'woocommerce'),
    ),
    'brahmanbaria' => array(
        __('Akhaura', 'woocommerce'),
        __('Banchharampur', 'woocommerce'),
        __('Bijoynagar', 'woocommerce'),
        __('Brahmanbaria Sadar', 'woocommerce'),
        __('Ashuganj', 'woocommerce'),
        __('Kasba', 'woocommerce'),
        __('Nabinagar', 'woocommerce'),
        __('Nasirnagar', 'woocommerce'),
        __('Sarail', 'woocommerce'),
    ),
    'chandpur' => array(
        __('Chandpur Sadar', 'woocommerce'),
        __('Faridganj', 'woocommerce'),
        __('Haim Char', 'woocommerce'),
        __('Hajiganj', 'woocommerce'),
        __('Kachua', 'woocommerce'),
        __('Matlab Dakshin', 'woocommerce'),
        __(' Matlab Uttar', 'woocommerce'),
        __('Shahrasti', 'woocommerce'),
    ),
    'chittagong' => array(
        __('Anowara', 'woocommerce'),
        __('Bayejid Bostami', 'woocommerce'),
        __('Banshkhali', 'woocommerce'),
        __('Bakalia', 'woocommerce'),
        __('Boalkhali', 'woocommerce'),
        __('Chandanaish', 'woocommerce'),
        __('Chandgaon', 'woocommerce'),
        __('Chittagong Port', 'woocommerce'),
        __('Double Mooring', 'woocommerce'),
        __('Fatikchhari', 'woocommerce'),
        __('Halishahar', 'woocommerce'),
        __('Hathazari', 'woocommerce'),
        __('Kotwali', 'woocommerce'),
        __('Khulshi', 'woocommerce'),
        __('Lohagara', 'woocommerce'),
        __('Mirsharai', 'woocommerce'),
        __('Pahartali', 'woocommerce'),
        __('Panchlaish', 'woocommerce'),
        __('Patiya', 'woocommerce'),
        __('Patenga', 'woocommerce'),
        __('Rangunia', 'woocommerce'),
        __('Raozan', 'woocommerce'),
        __('Sandwip', 'woocommerce'),
        __('Satkania', 'woocommerce'),
        __('Sitakunda', 'woocommerce'),
        __('Agrabad ', 'woocommerce'),
    ),
    'comilla' => array(
        __('Barura', 'woocommerce'),
        __('Brahman Para', 'woocommerce'),
        __('Burichang', 'woocommerce'),
        __('Chandina', 'woocommerce'),
        __('Chauddagram', 'woocommerce'),
        __('Comilla Sadar Dakshin', 'woocommerce'),
        __('Daudkandi', 'woocommerce'),
        __('Debidwar', 'woocommerce'),
        __('Homna', 'woocommerce'),
        __('Comilla Adarsha Sadar', 'woocommerce'),
        __('Laksam', 'woocommerce'),
        __('Manoharganj', 'woocommerce'),
        __('Meghna', 'woocommerce'),
        __('Muradnagar', 'woocommerce'),
        __('Nangalkot', 'woocommerce'),
        __('Titas', 'woocommerce'),
    ),
    'coxsbazar' => array(
        __('Chakaria', 'woocommerce'),
        __('Coxs Bazar Sadar', 'woocommerce'),
        __('Kutubdia', 'woocommerce'),
        __('Maheshkhali', 'woocommerce'),
        __('Pekua', 'woocommerce'),
        __('Ramu', 'woocommerce'),
        __('Teknaf', 'woocommerce'),
        __('Ukhia', 'woocommerce'),
    ),
    'feni' => array(
        __('Chhagalnaiya', 'woocommerce'),
        __('Daganbhuiyan', 'woocommerce'),
        __('Feni Sadar', 'woocommerce'),
        __('Fulgazi', 'woocommerce'),
        __('Parshuram', 'woocommerce'),
        __('Sonagazi', 'woocommerce'),
    ),
    'khagrachhari' => array(
        __('Dighinala', 'woocommerce'),
        __('Khagrachhari Sadar', 'woocommerce'),
        __('Lakshmichhari', 'woocommerce'),
        __('Mahalchhari', 'woocommerce'),
        __('Manikchhari', 'woocommerce'),
        __('Matiranga', 'woocommerce'),
        __('Panchhari', 'woocommerce'),
        __('Ramgarh', 'woocommerce'),
    ),
    'lakshmipur' => array(
        __('Kamalnagar', 'woocommerce'),
        __('Lakshmipur Sadar', 'woocommerce'),
        __('Roypur', 'woocommerce'),
        __('Ramganj', 'woocommerce'),
        __('Ramgati', 'woocommerce'),
    ),
    'noakhali' => array(
        __('Begumganj', 'woocommerce'),
        __('Chatkhil', 'woocommerce'),
        __('Companiganj', 'woocommerce'),
        __('Hatiya', 'woocommerce'),
        __('Kabirhat', 'woocommerce'),
        __('Senbagh', 'woocommerce'),
        __('Sonaimuri', 'woocommerce'),
        __('Subarnachar', 'woocommerce'),
        __('Noakhali Sadar', 'woocommerce'),
    ),
    'rangamati' => array(
        __('Baghaichhari', 'woocommerce'),
        __('Barkal Upazila', 'woocommerce'),
        __('Kawkhali (Betbunia)', 'woocommerce'),
        __('Belai Chhari Upazi', 'woocommerce'),
        __('Kaptai Upazila', 'woocommerce'),
        __('Jurai Chhari Upazil', 'woocommerce'),
        __('Langadu Upazila', 'woocommerce'),
        __('Naniarchar Upazila', 'woocommerce'),
        __('Rajasthali Upazila', 'woocommerce'),
        __('Rangamati Sadar Up', 'woocommerce'),
    ),
    'jamalpur' => array(
        __('Bakshiganj', 'woocommerce'),
        __('Dewanganj', 'woocommerce'),
        __('Islampur', 'woocommerce'),
        __('Jamalpur Sadar', 'woocommerce'),
        __('Madarganj', 'woocommerce'),
        __('Melandaha', 'woocommerce'),
        __('Sarishabari Upazila', 'woocommerce'),
    ),
    'mymensingh' => array(
        __('Bhaluka', 'woocommerce'),
        __('Dhobaura', 'woocommerce'),
        __('Fulbaria', 'woocommerce'),
        __('Gaffargaon', 'woocommerce'),
        __('Gauripur', 'woocommerce'),
        __('Haluaghat', 'woocommerce'),
        __('Ishwarganj', 'woocommerce'),
        __('Mymensingh Sadar', 'woocommerce'),
        __('Muktagachha', 'woocommerce'),
        __('Nandail', 'woocommerce'),
        __('Phulpur', 'woocommerce'),
        __('Trishal', 'woocommerce'),
    ),
    'netrakona' => array(
        __('Atpara', 'woocommerce'),
        __('Barhatta', 'woocommerce'),
        __('Durgapur', 'woocommerce'),
        __('Khaliajuri', 'woocommerce'),
        __('Kalmakanda', 'woocommerce'),
        __('Kendua', 'woocommerce'),
        __('Madan', 'woocommerce'),
        __('Mohanganj', 'woocommerce'),
        __('Netrokona Sadar', 'woocommerce'),
        __('Purbadhala', 'woocommerce'),
    ),
    'sherpur' => array(
        __('Jhenaigati', 'woocommerce'),
        __('Nakla', 'woocommerce'),
        __('Nalitabari', 'woocommerce'),
        __('Sherpur Sadar', 'woocommerce'),
        __('Sreebardi', 'woocommerce'),
    ),
    'bagerhat' => array(
        __('Bagerhat Sadar', 'woocommerce'),
        __('Chitalmari', 'woocommerce'),
        __('Fakirhat', 'woocommerce'),
        __('Kachua', 'woocommerce'),
        __('Mollahat', 'woocommerce'),
        __('Mongla', 'woocommerce'),
        __('Morrelganj', 'woocommerce'),
        __('Rampal', 'woocommerce'),
        __('Sarankhola', 'woocommerce'),
    ),
    'chuadanga' => array(
        __('Alamdanga', 'woocommerce'),
        __('Chuadanga Sadar', 'woocommerce'),
        __('Damurhuda', 'woocommerce'),
        __('Jiban Nagar', 'woocommerce'),
    ),
    'jessore' => array(
        __('Abhaynagar', 'woocommerce'),
        __('Bagher Para', 'woocommerce'),
        __('Chaugachha', 'woocommerce'),
        __('Jhikargachha', 'woocommerce'),
        __('Keshabpur', 'woocommerce'),
        __('Jessore Sadar', 'woocommerce'),
        __('Manirampur', 'woocommerce'),
        __('Sharsha', 'woocommerce'),
        __('Benapole', 'woocommerce'),
    ),
    'jhenaidah' => array(
        __('Harinakunda', 'woocommerce'),
        __('Jhenaidah Sadar', 'woocommerce'),
        __('Kaliganj', 'woocommerce'),
        __('Kotchandpur', 'woocommerce'),
        __('Maheshpur', 'woocommerce'),
        __('Shailkupa', 'woocommerce'),
    ),
    'khulna' => array(
        __('Batiaghata', 'woocommerce'),
        __('Dacope', 'woocommerce'),
        __('Daulatpur', 'woocommerce'),
        __('Dumuria', 'woocommerce'),
        __('Dighalia', 'woocommerce'),
        __('Khalishpur', 'woocommerce'),
        __('Khan Jahan Ali', 'woocommerce'),
        __('Khulna Sadar', 'woocommerce'),
        __('Koyra', 'woocommerce'),
        __('Paikgachha', 'woocommerce'),
        __('Phultala', 'woocommerce'),
        __('Rupsa', 'woocommerce'),
        __('Sonadanga', 'woocommerce'),
        __('Terokhada', 'woocommerce'),
    ),
    'kushtia' => array(
        __('Bheramara', 'woocommerce'),
        __('Daulatpur', 'woocommerce'),
        __('Khoksa', 'woocommerce'),
        __('Kumarkhali', 'woocommerce'),
        __('Kushtia Sadar', 'woocommerce'),
        __('Mirpur', 'woocommerce'),
    ),
    'magura' => array(
        __('Magura Sadar', 'woocommerce'),
        __('Mohammadpur', 'woocommerce'),
        __('Shalikha', 'woocommerce'),
        __('Sreepur', 'woocommerce'),
    ),
    'meherpur' => array(
        __('Gangni', 'woocommerce'),
        __('Mujib Nagar', 'woocommerce'),
        __('Meherpur Sadar', 'woocommerce'),
    ),
    'narail' => array(
        __('Kalia', 'woocommerce'),
        __('Lohagara', 'woocommerce'),
        __('Narail Sadar', 'woocommerce'),
    ),
    'satkhira' => array(
        __('Assasuni', 'woocommerce'),
        __('Debhata', 'woocommerce'),
        __('Kalaroa', 'woocommerce'),
        __('Kaliganj', 'woocommerce'),
        __('Satkhira Sadar', 'woocommerce'),
        __('Shyamnagar', 'woocommerce'),
        __('Tala', 'woocommerce'),
    ),
    'bogra' => array(
        __('Adamdighi', 'woocommerce'),
        __('Bogra Sadar', 'woocommerce'),
        __('Dhunat', 'woocommerce'),
        __('Dhupchanchia', 'woocommerce'),
        __('Gabtali', 'woocommerce'),
        __('Kahaloo', 'woocommerce'),
        __('Nandigram', 'woocommerce'),
        __('Sariakandi', 'woocommerce'),
        __('Shajahanpur', 'woocommerce'),
        __('Sherpur', 'woocommerce'),
        __('Shibganj', 'woocommerce'),
        __('Sonatola', 'woocommerce'),
    ),
    'chapainawabganj' => array(
        __('Bholahat', 'woocommerce'),
        __('Gomastapur', 'woocommerce'),
        __('Nachole', 'woocommerce'),
        __('Chapai Nababganj Sadar', 'woocommerce'),
        __('Shibganj', 'woocommerce'),
    ),
    'jaipurhat' => array(
        __('Akkelpur', 'woocommerce'),
        __('Joypurhat Sadar', 'woocommerce'),
        __('Kalai', 'woocommerce'),
        __('Khetlal', 'woocommerce'),
        __('Panchbibi', 'woocommerce'),
    ),
    'naogaon' => array(
        __('Atrai', 'woocommerce'),
        __('Badalgachhi', 'woocommerce'),
        __('Dhamoirhat', 'woocommerce'),
        __('Manda', 'woocommerce'),
        __('Mahadebpur', 'woocommerce'),
        __('Naogaon Sadar', 'woocommerce'),
        __('Niamatpur', 'woocommerce'),
        __('Patnitala', 'woocommerce'),
        __('Porsha', 'woocommerce'),
        __('Raninagar', 'woocommerce'),
        __('Sapahar', 'woocommerce'),
    ),
    'natore' => array(
        __('Bagatipara', 'woocommerce'),
        __('Baraigram', 'woocommerce'),
        __('Gurudaspur', 'woocommerce'),
        __('Lalpur', 'woocommerce'),
        __('Natore Sadar', 'woocommerce'),
        __('Singra', 'woocommerce'),
    ),
    'pabna' => array(
        __('Atgharia', 'woocommerce'),
        __('Bera', 'woocommerce'),
        __('Bhangura', 'woocommerce'),
        __('Chatmohar', 'woocommerce'),
        __('Faridpur', 'woocommerce'),
        __('Ishwardi', 'woocommerce'),
        __('Pabna Sadar', 'woocommerce'),
        __('Santhia', 'woocommerce'),
        __('Sujanagar', 'woocommerce'),
    ),
    'rajshahi' => array(
        __('Bagha', 'woocommerce'),
        __('Baghmara', 'woocommerce'),
        __('Boalia', 'woocommerce'),
        __('Charghat', 'woocommerce'),
        __('Durgapur', 'woocommerce'),
        __('Godagari', 'woocommerce'),
        __('Matihar', 'woocommerce'),
        __('Mohanpur', 'woocommerce'),
        __('Paba', 'woocommerce'),
        __('Puthia', 'woocommerce'),
        __('Rajpara', 'woocommerce'),
        __('Shah Makhdum', 'woocommerce'),
        __('Tanore', 'woocommerce'),
    ),
    'sirajganj' => array(
        __('Belkuchi', 'woocommerce'),
        __('Chauhali', 'woocommerce'),
        __('Kamarkhanda', 'woocommerce'),
        __('Kazipur', 'woocommerce'),
        __('Royganj', 'woocommerce'),
        __('Shahjadpur', 'woocommerce'),
        __('Sirajganj Sadar', 'woocommerce'),
        __('Tarash', 'woocommerce'),
        __('Ullah Para', 'woocommerce'),
    ),
    'dinajpur' => array(
        __('Birampur', 'woocommerce'),
        __('Birganj', 'woocommerce'),
        __('Biral', 'woocommerce'),
        __('Bochaganj', 'woocommerce'),
        __('Chirirbandar', 'woocommerce'),
        __('Fulbari', 'woocommerce'),
        __('Ghoraghat', 'woocommerce'),
        __('Hakimpur', 'woocommerce'),
        __('Kaharole', 'woocommerce'),
        __('Khansama', 'woocommerce'),
        __('Dinajpur Sadar', 'woocommerce'),
        __('Nawabganj', 'woocommerce'),
        __('Parbatipur', 'woocommerce'),
    ),
    'gaibandha' => array(
        __('Fulchhari', 'woocommerce'),
        __('Gaibandha Sadar', 'woocommerce'),
        __('Gobindaganj', 'woocommerce'),
        __('Palashbari', 'woocommerce'),
        __('Sadullapur', 'woocommerce'),
        __('Saghata', 'woocommerce'),
        __('Sundarganj', 'woocommerce'),
    ),
    'kurigram' => array(
        __('Bhurungamari', 'woocommerce'),
        __('Char Rajibpur', 'woocommerce'),
        __('Chilmari', 'woocommerce'),
        __('Phulbari', 'woocommerce'),
        __('Kurigram Sadar', 'woocommerce'),
        __('Nageshwari', 'woocommerce'),
        __('Rajarhat', 'woocommerce'),
        __('Raumari', 'woocommerce'),
        __('Ulipur', 'woocommerce'),
    ),
    'lalmonirhat' => array(
        __('Aditmari', 'woocommerce'),
        __('Hatibandha', 'woocommerce'),
        __('Kaliganj', 'woocommerce'),
        __('Lalmonirhat Sadar', 'woocommerce'),
        __('Patgram', 'woocommerce'),
    ),
    'nilphamari' => array(
        __('Dimla Upazila', 'woocommerce'),
        __('Domar Upazila', 'woocommerce'),
        __('Jaldhaka Upazila', 'woocommerce'),
        __('Kishoreganj Upazila', 'woocommerce'),
        __('Nilphamari Sadar Upaz', 'woocommerce'),
        __('Saidpur Upazila', 'woocommerce'),
    ),
    'panchagarh' => array(
        __('Atwari', 'woocommerce'),
        __('Boda', 'woocommerce'),
        __('Debiganj', 'woocommerce'),
        __('Panchagarh Sadar', 'woocommerce'),
        __('Tentulia', 'woocommerce'),
    ),
    'rangpur' => array(
        __('Badarganj', 'woocommerce'),
        __('Gangachara', 'woocommerce'),
        __('Kaunia', 'woocommerce'),
        __('Rangpur Sadar', 'woocommerce'),
        __('Mitha Pukur', 'woocommerce'),
        __('Pirgachha', 'woocommerce'),
        __('Pirganj', 'woocommerce'),
        __('Taraganj', 'woocommerce'),
    ),
    'thakurgaon' => array(
        __('Baliadangi', 'woocommerce'),
        __('Haripur', 'woocommerce'),
        __('Pirganj', 'woocommerce'),
        __('Ranisankail', 'woocommerce'),
        __('Thakurgaon Sadar', 'woocommerce'),
    ),
    'habiganj' => array(
        __('Ajmiriganj', 'woocommerce'),
        __('Bahubal', 'woocommerce'),
        __('Baniachong', 'woocommerce'),
        __('Chunarughat', 'woocommerce'),
        __('Habiganj Sadar', 'woocommerce'),
        __('Lakhai', 'woocommerce'),
        __('Madhabpur', 'woocommerce'),
        __('Nabiganj', 'woocommerce'),
    ),
    'maulvibazar' => array(
        __('Barlekha', 'woocommerce'),
        __('Juri', 'woocommerce'),
        __('Kamalganj', 'woocommerce'),
        __('Kulaura', 'woocommerce'),
        __('Maulvibazar Sadar', 'woocommerce'),
        __('Rajnagar', 'woocommerce'),
        __('Sreemangal', 'woocommerce'),
    ),
    'sunamganj' => array(
        __('Bishwambarpur', 'woocommerce'),
        __('Chhatak', 'woocommerce'),
        __('Dakshin Sunamganj', 'woocommerce'),
        __('Derai', 'woocommerce'),
        __('Dharampasha', 'woocommerce'),
        __('Dowarabazar', 'woocommerce'),
        __('Jagannathpur', 'woocommerce'),
        __('Jamalganj', 'woocommerce'),
        __('Sulla', 'woocommerce'),
        __('Sunamganj Sadar', 'woocommerce'),
        __('Tahirpur', 'woocommerce'),
    ),
    'sylhet' => array(
        __('Balaganj', 'woocommerce'),
        __('Beani Bazar', 'woocommerce'),
        __('Bishwanath', 'woocommerce'),
        __('Companiganj', 'woocommerce'),
        __('Dakshin Surma', 'woocommerce'),
        __('Fenchuganj', 'woocommerce'),
        __('Golapganj', 'woocommerce'),
        __('Gowainghat', 'woocommerce'),
        __('Jaintiapur', 'woocommerce'),
        __('Kanaighat', 'woocommerce'),
        __('Sylhet Sadar', 'woocommerce'),
        __('Zakiganj', 'woocommerce'),
    ),
    'saver' => array(
        __('Savar Bus Stand', 'woocommerce'),
        __('Radio Collony', 'woocommerce'),
        __('Rajashon', 'woocommerce'),
        __('Enam Medical', 'woocommerce'),
        __('Anondopur', 'woocommerce'),
        __('Savar Bazar Road', 'woocommerce'),
        __('Namabazar', 'woocommerce'),
        __('Bank Collony', 'woocommerce'),
        __('Arapara', 'woocommerce'),
        __('Kashimpur', 'woocommerce'),
        __('Savar-Ashulia', 'woocommerce'),
        __('Nabinagar', 'woocommerce'),
        __('Jahangirnagar', 'woocommerce'),
        __('Narsinghopur', 'woocommerce'),
        __('Jamgora', 'woocommerce'),
        __('Polli Biddyut', 'woocommerce'),
        __('Baipail', 'woocommerce'),
        __('Jirabo', 'woocommerce'),
        __('Jirani', 'woocommerce'),
        __('Dhamrai', 'woocommerce'),
    ),
);

function enqueue_scripts()
{
    wp_enqueue_script('jquery');
    wp_enqueue_script('select2', 'https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/js/select2.min.js', array('jquery'), '4.0.13', true);
    wp_enqueue_script('place-select-js', plugin_dir_url(__FILE__) . 'js/place-select.js', array('jquery', 'select2'), '0.1', true);
}
add_action('admin_enqueue_scripts', 'enqueue_scripts');


add_filter('woocommerce_admin_billing_fields', 'admin_billing_city_select_field');
function admin_billing_city_select_field($fields)
{
    global $pagenow, $places;

    // Only for new order creation
    if ($pagenow != 'post-new.php') return $fields;

    $options = array('' => __('Select a city&hellip;', 'woocommerce'));
    if (isset($places)) {
        foreach ($places as $state => $cities) {
            foreach ($cities as $city => $city_name) {
                $options[$city] = $city_name[0];
            }
        }
    }

    $fields['city'] = array(
        'label'   => __('City', 'woocommerce'),
        'show'    => false,
        'class'   => 'js_field-city select short',
        'type'    => 'select',
        'options' => $options,
    );
    return $fields;
}
